// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "GPU Telemetry Pipeline"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/gpus": {
            "get": {
                "description": "Returns a list of all unique GPUs that have reported telemetry",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GPUs"
                ],
                "summary": "List all GPUs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gpu-telemetry-pipeline_gateway_internal_models.GPUListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gpu-telemetry-pipeline_gateway_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/gpus/{id}/telemetry": {
            "get": {
                "description": "Returns telemetry data for a specific GPU, ordered by timestamp descending",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telemetry"
                ],
                "summary": "Get GPU telemetry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "GPU UUID (e.g., GPU-5fd4f087-86f3-7a43-b711-4771313afc50)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start time filter (formats: 2026-01-28T00:00:00, 2026-01-28, or Unix timestamp)",
                        "name": "start_time",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time filter (formats: 2026-01-28T23:59:59, 2026-01-28, or Unix timestamp)",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Max records to return (default 100, max 1000)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of records to skip (for pagination)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gpu-telemetry-pipeline_gateway_internal_models.TelemetryListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_gpu-telemetry-pipeline_gateway_internal_models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_gpu-telemetry-pipeline_gateway_internal_models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_gpu-telemetry-pipeline_gateway_internal_models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API and its dependencies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_gpu-telemetry-pipeline_gateway_internal_models.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_gpu-telemetry-pipeline_gateway_internal_models.ErrorResponse": {
            "description": "API error response",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 404
                },
                "details": {
                    "type": "string",
                    "example": "GPU-invalid-uuid"
                },
                "error": {
                    "type": "string",
                    "example": "GPU not found"
                }
            }
        },
        "github_com_gpu-telemetry-pipeline_gateway_internal_models.GPU": {
            "description": "GPU information",
            "type": "object",
            "properties": {
                "device": {
                    "type": "string",
                    "example": "nvidia0"
                },
                "gpu_index": {
                    "type": "integer",
                    "example": 0
                },
                "hostname": {
                    "type": "string",
                    "example": "mtv5-dgx1-hgpu-031"
                },
                "last_seen": {
                    "type": "string",
                    "example": "2026-01-28T15:30:00Z"
                },
                "model_name": {
                    "type": "string",
                    "example": "NVIDIA H100 80GB HBM3"
                },
                "uuid": {
                    "type": "string",
                    "example": "GPU-5fd4f087-86f3-7a43-b711-4771313afc50"
                }
            }
        },
        "github_com_gpu-telemetry-pipeline_gateway_internal_models.GPUListResponse": {
            "description": "List of GPUs response",
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 8
                },
                "gpus": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_gpu-telemetry-pipeline_gateway_internal_models.GPU"
                    }
                }
            }
        },
        "github_com_gpu-telemetry-pipeline_gateway_internal_models.GPUTelemetry": {
            "description": "GPU telemetry data point",
            "type": "object",
            "properties": {
                "container": {
                    "type": "string"
                },
                "device": {
                    "type": "string",
                    "example": "nvidia0"
                },
                "gpu_index": {
                    "type": "integer",
                    "example": 0
                },
                "hostname": {
                    "type": "string",
                    "example": "mtv5-dgx1-hgpu-031"
                },
                "id": {
                    "type": "string",
                    "example": "abc123-def456"
                },
                "labels_raw": {
                    "type": "string"
                },
                "message_id": {
                    "type": "string"
                },
                "metric_name": {
                    "type": "string",
                    "example": "DCGM_FI_DEV_GPU_UTIL"
                },
                "model_name": {
                    "type": "string",
                    "example": "NVIDIA H100 80GB HBM3"
                },
                "namespace": {
                    "type": "string"
                },
                "pod": {
                    "type": "string"
                },
                "received_at": {
                    "type": "string",
                    "example": "2026-01-28T15:30:01Z"
                },
                "timestamp": {
                    "type": "string",
                    "example": "2026-01-28T15:30:00Z"
                },
                "uuid": {
                    "type": "string",
                    "example": "GPU-5fd4f087-86f3-7a43-b711-4771313afc50"
                },
                "value": {
                    "type": "number",
                    "example": 75.5
                }
            }
        },
        "github_com_gpu-telemetry-pipeline_gateway_internal_models.HealthResponse": {
            "description": "Health check response",
            "type": "object",
            "properties": {
                "database": {
                    "type": "string",
                    "example": "healthy"
                },
                "status": {
                    "type": "string",
                    "example": "healthy"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "github_com_gpu-telemetry-pipeline_gateway_internal_models.TelemetryListResponse": {
            "description": "GPU telemetry response with pagination",
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 100
                },
                "end_time": {
                    "type": "string"
                },
                "gpu_uuid": {
                    "type": "string",
                    "example": "GPU-5fd4f087-86f3-7a43-b711-4771313afc50"
                },
                "start_time": {
                    "type": "string"
                },
                "telemetry": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_gpu-telemetry-pipeline_gateway_internal_models.GPUTelemetry"
                    }
                },
                "total_count": {
                    "type": "integer",
                    "example": 1000
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "GPU Telemetry API",
	Description:      "REST API for querying GPU telemetry data from the GPU Telemetry Pipeline.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
